FROM postgres:18

USER root
RUN apt-get update && \
    apt-get install -y postgresql-18-cron && \
    rm -rf /var/lib/apt/lists/*

USER postgres
CMD ["postgres", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=postgres"]