CREATE TABLE IF NOT EXISTS "messages" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY 
        (SEQUENCE NAME "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "created_at" timestamp DEFAULT now() NOT NULL,
    "room_id" text NOT NULL,
    "cipher_text" text NOT NULL,
    "user_id" text NOT NULL,
    "iv" text NOT NULL
);

CREATE TABLE IF NOT EXISTS "rooms" (
    "id" text PRIMARY KEY NOT NULL,
    "expired_at" timestamp DEFAULT NOW() + INTERVAL '10 minutes' NOT NULL,
    "users" jsonb NOT NULL,
    "public_keys" json NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'rooms_max_users'
    ) THEN
        ALTER TABLE "rooms"
        ADD CONSTRAINT "rooms_max_users"
        CHECK (jsonb_array_length("users") <= 2);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'messages_room_id_rooms_id_fk'
    ) THEN
        ALTER TABLE "messages"
        ADD CONSTRAINT "messages_room_id_rooms_id_fk"
        FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
    END IF;
END
$$;
