name: Build and deploy

on:
    push:
        branches: ["main"]

env:
    WEBSITE_IMAGE_NAME: ghcr.io/jesseogunlaja/whispr
    POSTGRES_IMAGE_NAME: ghcr.io/jesseogunlaja/whispr-postgres

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun ci

            - name: Run dev server
              run: docker compose -f docker/docker-compose.staging.yaml up -d
              env:
                  STREAMTHING_SERVER_PASSWORD: ${{ secrets.STREAMTHING_SERVER_PASSWORD }}

            - name: Run tests
              run: bun run test

            - name: Stop dev server
              if: always()
              run: docker compose down

    build:
        needs: test
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push image
              uses: docker/build-push-action@v6
              with:
                  file: docker/Dockerfile
                  push: true
                  tags: |
                      ${{ env.WEBSITE_IMAGE_NAME }}:latest
                      ${{ env.WEBSITE_IMAGE_NAME }}:${{ github.sha }}

            - name: Build and push postgres image
              uses: docker/build-push-action@v6
              with:
                  file: docker/Dockerfile.postgres
                  push: true
                  tags: |
                      ${{ env.POSTGRES_IMAGE_NAME }}:latest
                      ${{ env.POSTGRES_IMAGE_NAME }}:${{ github.sha }}

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - name: Copy docker-compose.yaml to server
              uses: appleboy/scp-action@v1
              with:
                  host: ${{ vars.SERVER_HOST }}
                  username: root
                  password: ${{ secrets.SSH_PASSWORD }}
                  strip_components: 1
                  source: "docker/docker-compose.yaml"
                  target: "/opt/whispr"

            - name: Deploy to server
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ vars.SERVER_HOST }}
                  username: root
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd /opt/whispr
                      docker compose up -d --force-recreate --pull always website postgres
